export const TAB_RECORD = 'TAB_RECORD'
export const USER_ACCOUNT_ID = 'USER_ACCOUNT_ID'
export const TOKEN = 'TOKEN'
export const SIDE_BAR = 'SIDE_BAR'
export const TAG_VIEW = 'TAG_VIEW'
export const ADD_TAG_VIEW = 'ADD_TAG_VIEW'
export const DEL_TAG_VIEW = 'DEL_TAG_VIEW'
